development:
  clients:
    default:
      database: development
      hosts:
        - localhost:3000
      options:

test:
  clients:
    default:
      database: teste_backend_test
      hosts:
        - localhost:3000
      options:
        read:
          mode: :primary
        max_pool_size: 1
